[package]
name = "veh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
image = "0.25.1"
pollster = "0.3.0"
vello = "0.1.0"
vello_svg = "0.1.0"
wgpu = "0.19.4"
winit = "0.29.0"